#!/bin/bash

# Script to generate API configuration at build time
# This script is automatically called during the build process via Xcode Build Rules
# to inject the API key securely into the compiled application

set -e

# Determine project directory and output location - works with both manual execution and Xcode build rules
if [ -n "$SRCROOT" ] && [ -n "$DERIVED_FILE_DIR" ]; then
    # Running from Xcode build system
    PROJECT_DIR="$SRCROOT"
    OUTPUT_FILE="$DERIVED_FILE_DIR/GeneratedConfiguration.swift"
    echo "🔨 Running from Xcode build system"
    echo "📁 Output: $OUTPUT_FILE"
else
    # Running manually
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
    PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
    CONFIG_DIR="$PROJECT_DIR/Brixie/Configuration/Generated"
    mkdir -p "$CONFIG_DIR"
    OUTPUT_FILE="$CONFIG_DIR/GeneratedConfiguration.swift"
    echo "🔧 Running manually"
fi

# Check for .env file first
if [ -f "$PROJECT_DIR/.env" ]; then
    echo "Loading environment from .env file..."
    source "$PROJECT_DIR/.env"
fi

# Get API key from environment variable (could be from .env or system env)
API_KEY="${REBRICKABLE_API_KEY:-}"

if [ -n "$API_KEY" ]; then
    echo "🔐 Generating build configuration with embedded API key..."
    cat > "$OUTPUT_FILE" << EOF
// GENERATED FILE - DO NOT EDIT
// This file is automatically generated during build time
// Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

import Foundation

struct GeneratedConfiguration {
    static let rebrickableAPIKey: String? = "$API_KEY"
    static let hasEmbeddedAPIKey = true
    static let buildDate = "$( date -u +"%Y-%m-%d %H:%M:%S UTC" )"
}
EOF
    echo "✅ API configuration generated successfully with embedded key"
else
    echo "⚠️  No REBRICKABLE_API_KEY environment variable found"
    echo "🔧 Generating build configuration without embedded API key..."
    cat > "$OUTPUT_FILE" << EOF
// GENERATED FILE - DO NOT EDIT  
// This file is automatically generated during build time
// Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

import Foundation

struct GeneratedConfiguration {
    static let rebrickableAPIKey: String? = nil
    static let hasEmbeddedAPIKey = false
    static let buildDate = "$( date -u +"%Y-%m-%d %H:%M:%S UTC" )"
}
EOF
    echo "⚠️  API configuration generated without embedded key"
fi

echo "📁 Generated file: $OUTPUT_FILE"
echo "🚀 Ready for build!"