name: Deploy

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    name: Deploy - ${{ matrix.platform }}
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        platform: [iOS, macOS]
        include:
          - platform: iOS
            lane: build_ios
          - platform: macOS
            lane: build_macos
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
    env:
      REBRICKABLE_API_KEY: ${{ secrets.REBRICKABLE_API_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      FASTLANE_SKIP_UPDATE_CHECK: 1
      FASTLANE_HIDE_GITHUB_ISSUES: 1
      FASTLANE_HIDE_CHANGELOG: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Show Deployment Environment
        run: |
          echo "🚀 Deployment Environment Info:"
          echo "Platform: ${{ matrix.platform }}"
          echo "Lane: ${{ matrix.lane }}"
          echo "Branch/Tag: ${{ github.ref }}"
          echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "Xcode Version: $(xcodebuild -version)"
          echo ""

      - name: Build Release App with Fastlane
        run: |
          echo "🏗️ Building ${{ matrix.platform }} app for deployment..."
          bundle exec fastlane ios ${{ matrix.lane }}

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brixie-${{ matrix.platform }}-${{ github.sha }}
          path: |
            *.app
            *.dSYM
          retention-days: 30